# Generated by Django 4.1.5 on 2023-07-31 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_username_user_user_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="start_date",
        ),
    ]
