# Generated by Django 4.1.5 on 2023-07-31 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
