# Generated by Django 4.1.5 on 2023-07-29 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0002_alter_show_genres_alter_show_producers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="genres",
            field=models.ManyToManyField(blank=True, to="base.genre"),
        ),
        migrations.AlterField(
            model_name="show",
            name="producers",
            field=models.ManyToManyField(blank=True, to="base.producer"),
        ),
        migrations.AlterField(
            model_name="show",
            name="studio",
            field=models.ManyToManyField(blank=True, to="base.studio"),
        ),
        migrations.AlterField(
            model_name="show",
            name="tags",
            field=models.ManyToManyField(blank=True, to="base.tag"),
        ),
        migrations.CreateModel(
            name="UserShowList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("watching", "Watching"),
                            ("planning", "Planning"),
                            ("paused", "Paused"),
                            ("dropped", "Dropped"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (None, "Not Scored"),
                            (1, "1 - Very Poor"),
                            (2, "2 - Poor"),
                            (3, "3 - Below Average"),
                            (4, "4 - Average"),
                            (5, "5 - Above Average"),
                            (6, "6 - Good"),
                            (7, "7 - Very Good"),
                            (8, "8 - Great"),
                            (9, "9 - Excellent"),
                            (10, "10 - Masterpiece"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                ("progress", models.PositiveIntegerField(default=0)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("complete_date", models.DateField(blank=True, null=True)),
                ("is_favorite", models.BooleanField(default=False)),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.show"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="show_list",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
