# Generated by Django 4.1.5 on 2023-07-29 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_alter_show_genres_alter_show_producers_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usershowlist",
            old_name="is_favorite",
            new_name="favorite",
        ),
        migrations.RenameField(
            model_name="usershowlist",
            old_name="show",
            new_name="show_id",
        ),
        migrations.RenameField(
            model_name="usershowlist",
            old_name="user",
            new_name="user_id",
        ),
    ]
