# Generated by Django 4.1.5 on 2023-07-31 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_usershowlist_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usershowlist",
            old_name="show_id",
            new_name="show",
        ),
        migrations.RenameField(
            model_name="usershowlist",
            old_name="user_id",
            new_name="user",
        ),
    ]
