# Generated by Django 4.1.5 on 2023-07-31 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_rename_show_id_usershowlist_show_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usershowlist",
            old_name="show",
            new_name="show_id",
        ),
        migrations.RenameField(
            model_name="usershowlist",
            old_name="user",
            new_name="user_id",
        ),
    ]
